services:
  client:
    build: .
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - '5173:5173'
    environment:
      VITE_SERVER_URL: http://localhost:3000

volumes:
  node_modules:
